services:
    db_pandabize:
        platform: linux/x86_64
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3307:3306"
    app:
        build: .
        command: bash -c "rm -f tmp/pids/server.pid && gem install bundler && bundle install && bundle exec rails s -b 0.0.0.0"
        volumes:
            - ".:/app"
        ports:
            - "3001:3000"
        depends_on:
            - db_pandabize
        links:
            - db_pandabize
        environment:
            DB_USER: root
            DB_NAME: app
            DB_PASSWORD: password
            DB_HOST: db_pandabize
